const $=s=>document.querySelector(s);const apiToken=$('#apiToken'),clearToken=$('#clearToken');const cancel=$('#cancel');const input=$('#input'),files=$('#files'),mode=$('#mode'),run=$('#run'),timeline=$('#timeline'),answer=$('#answer'),sources=$('#sources'),state=$('#taskState'),confidence=$('#confidence'),error=$('#error'),health=$('#health');
function authHeaders(extra={}){const h={'content-type':'application/json',...extra};const t=apiToken?.value.trim();if(t)h.authorization=`Bearer ${t}`;return h}async function healthCheck(){try{const r=await fetch('/health');const x=await r.json();health.textContent=`Core ${x.version} • ${x.capabilities.length} capabilities`}catch{health.textContent='Core offline'}}healthCheck();
function addEvent(title,detail=''){if(timeline.querySelector('.empty'))timeline.innerHTML='';const el=document.createElement('div');el.className='event';el.innerHTML=`<b>${escapeHtml(title)}</b>${detail?` — ${escapeHtml(detail)}`:''}`;timeline.prepend(el)}function escapeHtml(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function renderSources(items=[]){sources.innerHTML='';if(!items.length){sources.innerHTML='<div class="empty">No evidence returned.</div>';return}for(const e of items){const d=document.createElement('div');d.className='source';d.innerHTML=`<a href="${escapeHtml(e.source)}" target="_blank" rel="noreferrer">${escapeHtml(e.source)}</a><small>${escapeHtml(e.claim)} • ${(Number(e.confidence)*100).toFixed(0)}% confidence</small>`;sources.appendChild(d)}}
async function streamEvents(taskId,signal){const r=await fetch(`/v1/events?taskId=${encodeURIComponent(taskId)}`,{headers:authHeaders(),signal});if(!r.ok)throw new Error(`Event stream failed (${r.status})`);const reader=r.body.getReader(),decoder=new TextDecoder();let buf='';while(true){const {value,done}=await reader.read();if(done)break;buf+=decoder.decode(value,{stream:true});const chunks=buf.split('\n\n');buf=chunks.pop()||'';for(const chunk of chunks){const line=chunk.split('\n').find(x=>x.startsWith('data: '));if(!line)continue;try{const ev=JSON.parse(line.slice(6));if(ev.type==='connected')continue;const d=ev.data;if(ev.type==='token'){answer.textContent+=(d.text||'');continue;}if(ev.type==='plan')addEvent('Plan created',`${d.steps?.length??0} expert step(s)`);else if(ev.type==='evidence')addEvent('Evidence collected',`${d.length??0} item(s)`);else if(ev.type==='files')addEvent('Files attached',`${d.length??0} file(s)`);else if(ev.type==='expert')addEvent('Expert executed',d.expert);else if(ev.type==='critique')addEvent('Critique',`score ${d.score}`);else if(ev.type==='final')addEvent('Verified final',d.status);else if(ev.type==='error')addEvent('Execution error',Array.isArray(d)?d.join('; '):String(d));}catch{}}}}
async function runTask(){const text=input.value.trim();if(!text)return;run.disabled=true;error.textContent='';state.textContent='Running';confidence.textContent='—';answer.textContent='';sources.innerHTML='<div class="empty">Collecting evidence…</div>';timeline.innerHTML='';const id='web-'+Date.now();window.__jalalaiTaskId=id;cancel.disabled=false;addEvent('Task accepted',mode.value.toUpperCase());const controller=new AbortController();window.__jalalaiStreamController=controller;const stream=streamEvents(id,controller.signal).catch(e=>{if(e.name!=='AbortError')addEvent('Event stream',e.message)});
try{const attachments=[];for(const f of (files?.files??[])){if(f.size>250000)throw new Error(`${f.name}: file too large (max 250 KB)`);attachments.push({id:`file-${Date.now()}-${Math.random().toString(36).slice(2)}`,name:f.name,type:f.type,size:f.size,text:await f.text()});}const r=await fetch('/v1/tasks',{method:'POST',headers:authHeaders({'x-client-id':'web-command-center'}),body:JSON.stringify({id,input:text,mode:mode.value,attachments})});const out=await r.json();if(!r.ok)throw new Error(out.error||'Task failed');if(out.answer)answer.textContent=out.answer||'';else if(!answer.textContent)answer.textContent=out.errors?.join('\n')||'No answer returned.';confidence.textContent=out.confidence!=null?`${Math.round(out.confidence*100)}%`:'—';renderSources(out.evidence);state.textContent=out.status;addEvent('Task finished',out.status);if(out.errors?.length)error.textContent=out.errors.join(' • ');}catch(e){state.textContent='failed';error.textContent=e.message;addEvent('Request failed',e.message)}finally{controller.abort();await stream.catch(()=>{});run.disabled=false;cancel.disabled=true}}

cancel.onclick=async()=>{try{window.__jalalaiStreamController?.abort();await fetch('/v1/tasks/'+encodeURIComponent(window.__jalalaiTaskId),{method:'DELETE',headers:authHeaders()});addEvent('Cancellation requested')}catch(e){error.textContent=e.message}};run.onclick=runTask;input.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key==='Enter')runTask()});

clearToken?.addEventListener('click',()=>{if(apiToken)apiToken.value='';apiToken?.focus()});

// ---------- Simple / Advanced view toggle (persisted, purely presentational) ----------
(function(){
  const VIEW_KEY='jalalai_ui_view';
  const btnSimple=document.getElementById('viewSimple'),btnAdvanced=document.getElementById('viewAdvanced');
  const modeSelect=document.getElementById('mode');
  function applyView(view){
    document.body.classList.toggle('simple-mode',view==='simple');
    btnSimple.classList.toggle('active',view==='simple');
    btnAdvanced.classList.toggle('active',view!=='simple');
    btnSimple.setAttribute('aria-pressed',String(view==='simple'));
    btnAdvanced.setAttribute('aria-pressed',String(view!=='simple'));
    if(view==='simple'&&modeSelect)modeSelect.value='deep'; // sensible default when the picker is hidden
  }
  btnSimple.onclick=()=>{localStorage.setItem(VIEW_KEY,'simple');applyView('simple')};
  btnAdvanced.onclick=()=>{localStorage.setItem(VIEW_KEY,'advanced');applyView('advanced')};
  applyView(localStorage.getItem(VIEW_KEY)||'simple');
})();