import {existsSync,readFileSync,mkdirSync,writeFileSync} from 'node:fs';
function parent(p:string){const i=Math.max(p.lastIndexOf('/'),p.lastIndexOf('\\'));return i>0?p.slice(0,i):'.'}
export type RuntimeJobStatus='queued'|'awaiting_approval'|'running'|'completed'|'failed'|'cancelled';
export interface RuntimeJob<T=unknown>{id:string;status:RuntimeJobStatus;createdAt:number;updatedAt:number;attempts:number;maxAttempts:number;requireApproval:boolean;result?:T;error?:string;startedAt?:number;finishedAt?:number}
interface Approval{jobId:string;createdAt:number;approvedAt?:number;rejectedAt?:number;status:'pending'|'approved'|'rejected';reason?:string}
export class ProductionRuntime<T=unknown>{
 private jobs=new Map<string,RuntimeJob<T>>(); private approvals=new Map<string,Approval>(); private queue:string[]=[]; private active=0; private waiters=new Map<string,Array<(v:T)=>void>>();
 constructor(private handler:(job:RuntimeJob<T>,signal:AbortSignal)=>Promise<T>,private path=process.env.JALALAI_RUNTIME_PATH??'./data/jalalai-runtime.json',private concurrency=Math.max(1,Math.min(16,Number(process.env.JALALAI_WORKERS??4))),private defaultMaxAttempts=3){}
 async load(){try{if(existsSync(this.path)){const raw=JSON.parse(readFileSync(this.path,'utf8'));for(const j of raw?.jobs??[])this.jobs.set(j.id,j);for(const a of raw?.approvals??[])this.approvals.set(a.jobId,a);this.queue=[...(raw?.queue??[])].filter((id:string)=>this.jobs.get(id)?.status==='queued'||this.jobs.get(id)?.status==='awaiting_approval');for(const j of this.jobs.values())if(j.status==='running'){j.status='queued';j.updatedAt=Date.now();this.queue.push(j.id)}}}catch{}await this.persist();this.pump();return this}
 private async persist(){try{mkdirSync(parent(this.path),{recursive:true});writeFileSync(this.path,JSON.stringify({jobs:[...this.jobs.values()],approvals:[...this.approvals.values()],queue:this.queue},null,2))}catch{} }
 enqueue(id:string,requireApproval=false,maxAttempts=this.defaultMaxAttempts,metadata:Record<string,unknown>={}){if(this.jobs.has(id))throw new Error('runtime_job_exists');const now=Date.now();const job:RuntimeJob<T>={id,status:requireApproval?'awaiting_approval':'queued',createdAt:now,updatedAt:now,attempts:0,maxAttempts:Math.max(1,Math.min(5,maxAttempts)),requireApproval};Object.assign(job,metadata);this.jobs.set(id,job);if(requireApproval)this.approvals.set(id,{jobId:id,createdAt:now,status:'pending'});else this.queue.push(id);void this.persist();this.pump();return job}
 private pump(){while(this.active<this.concurrency&&this.queue.length){const id=this.queue.shift()!;const job=this.jobs.get(id);if(!job||job.status!=='queued')continue;void this.run(job)}}
 private async run(job:RuntimeJob<T>){this.active++;job.status='running';job.startedAt=Date.now();job.updatedAt=Date.now();job.attempts++;await this.persist();const controller=new AbortController();(job as any)._controller=controller;try{job.result=await this.handler(job,controller.signal);job.status='completed';job.finishedAt=Date.now();job.updatedAt=Date.now();this.resolve(job.id,job.result)}catch(e){job.error=e instanceof Error?e.message:String(e);job.updatedAt=Date.now();if(job.error==='task_cancelled'){job.status='cancelled';job.finishedAt=Date.now()}else if(job.attempts<job.maxAttempts){job.status='queued';this.queue.push(job.id)}else{job.status='failed';job.finishedAt=Date.now()}if(job.status==='failed'||job.status==='cancelled')this.rejectWait(job.id,new Error(job.error))}finally{delete (job as any)._controller;this.active--;await this.persist();this.pump()}}
 approve(id:string,reason?:string){const j=this.jobs.get(id);const a=this.approvals.get(id);if(!j||!a)throw new Error('approval_not_found');if(a.status!=='pending')return j;a.status='approved';a.approvedAt=Date.now();a.reason=reason;j.status='queued';j.updatedAt=Date.now();this.queue.push(id);void this.persist();this.pump();return j}
 reject(id:string,reason='rejected'){const j=this.jobs.get(id);const a=this.approvals.get(id);if(!j||!a)throw new Error('approval_not_found');a.status='rejected';a.rejectedAt=Date.now();a.reason=reason;j.status='failed';j.error=reason;j.finishedAt=Date.now();j.updatedAt=Date.now();void this.persist();this.rejectWait(id,new Error(reason));return j}
 cancel(id:string){const j=this.jobs.get(id);if(!j)throw new Error('runtime_job_not_found');if(j.status==='running'&&(j as any)._controller)(j as any)._controller.abort();else if(j.status==='queued'||j.status==='awaiting_approval'){j.status='cancelled';j.finishedAt=Date.now();j.updatedAt=Date.now();this.queue=this.queue.filter(x=>x!==id);this.rejectWait(id,new Error('task_cancelled'));void this.persist()}return j}
 wait(id:string,timeoutMs=0):Promise<T>{const j=this.jobs.get(id);if(!j) return Promise.reject(new Error('runtime_job_not_found'));if(j.status==='completed')return Promise.resolve(j.result as T);if(['failed','cancelled'].includes(j.status))return Promise.reject(new Error(j.error??j.status));return new Promise<T>((resolve,reject)=>{const list=this.waiters.get(id)??[];this.waiters.set(id,[...list,resolve]);if(timeoutMs>0)setTimeout(()=>reject(new Error('runtime_wait_timeout')),timeoutMs)})}
 private resolve(id:string,v:T){for(const f of this.waiters.get(id)??[])f(v);this.waiters.delete(id)}
 private rejectWait(id:string,e:Error){for(const f of this.waiters.get(id)??[])void Promise.reject(e);this.waiters.delete(id)}
 get(id:string){return this.jobs.get(id)}list(){return [...this.jobs.values()].sort((a,b)=>b.createdAt-a.createdAt)}approvalsList(){return [...this.approvals.values()].sort((a,b)=>b.createdAt-a.createdAt)}stats(){const counts:Record<string,number>={};for(const j of this.jobs.values())counts[j.status]=(counts[j.status]??0)+1;return {concurrency:this.concurrency,active:this.active,queued:this.queue.length,counts}}
}
