export const EXPERT_DOMAINS = [
    'hr', 'accounting', 'finance', 'payroll', 'tax', 'audit', 'business', 'management', 'law', 'programming', 'software-engineering', 'cybersecurity', 'mathematics', 'statistics', 'science', 'medicine', 'education', 'research', 'marketing', 'sales', 'operations', 'project-management', 'data-analysis', 'ai-ml', 'engineering', 'architecture', 'writing', 'translation', 'media', 'design', 'productivity', 'travel', 'general-knowledge', 'strategic-reasoning'
];
const aliases = { hr: ['human resources', 'employee', 'recruitment', 'hiring'], accounting: ['accounts', 'ledger', 'journal', 'invoice', 'bookkeeping'], finance: ['financial', 'investment', 'budget'], payroll: ['salary', 'wages'], tax: ['taxation', 'vat', 'gst'], audit: ['auditing'], law: ['legal', 'contract'], programming: ['code', 'coding', 'javascript', 'python', 'typescript'], 'software-engineering': ['software', 'api', 'backend', 'frontend', 'architecture'], cybersecurity: ['security', 'vulnerability', 'penetration'], mathematics: ['math', 'equation', 'algebra'], statistics: ['statistical', 'probability'], science: ['physics', 'chemistry', 'biology'], medicine: ['medical', 'doctor', 'diagnosis'], education: ['teaching', 'student', 'course'], research: ['research', 'sources', 'study', 'latest'], marketing: ['campaign', 'seo', 'advertising'], sales: ['selling', 'customer'], operations: ['process', 'workflow'], 'project-management': ['project', 'milestone'], 'data-analysis': ['data', 'dataset', 'analytics'], 'ai-ml': ['machine learning', 'llm', 'artificial intelligence'], engineering: ['mechanical', 'electrical', 'civil'], architecture: ['building', 'structural design'], writing: ['write', 'rewrite', 'essay'], translation: ['translate', 'language'], media: ['video', 'audio'], design: ['ui', 'ux', 'graphic'], productivity: ['schedule', 'organize'], travel: ['trip', 'flight', 'hotel'], business: ['company', 'startup', 'business'], management: ['manager', 'leadership'] };
const definitions = EXPERT_DOMAINS.map((domain, i) => ({ id: `expert.${domain}`, name: `${domain.replaceAll('-', ' ')} expert`, domains: [domain], skills: ['analysis', 'synthesis'], priority: 100 - i, requiredTools: domain === 'research' ? ['web.search', 'web.open'] : [], verification: ['critic.review', 'confidence.score'] }));
export class AgentRegistry {
    agents = new Map(definitions.map(a => [a.id, a]));
    register(a) { this.agents.set(a.id, a); }
    get(id) { return this.agents.get(id); }
    list() { return [...this.agents.values()]; }
    select(domains, limit = 4) { return this.list().filter(a => a.domains.some(d => domains.includes(d))).sort((a, b) => b.priority - a.priority).slice(0, limit); }
    detect(input) { const s = input.toLowerCase(); return EXPERT_DOMAINS.filter(d => s.includes(d) || aliases[d]?.some(x => s.includes(x))); }
}
